import {renderDirectoryPage} from './directory-shell.js';
import {collectionRepository} from './collection-repository.js';
import {escape,jsonData} from './profile-components.js';

const headers={'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
function dialogs(){return `<dialog id="collection-editor" aria-labelledby="collection-editor-title"><form id="collection-edit-form"><h2 id="collection-editor-title">Collection</h2><label>Name<input name="name" maxlength="160" required></label><label>Summary<textarea name="summary" rows="3" maxlength="10000"></textarea></label><label>Artwork URL<input name="coverUrl" type="url" maxlength="2048" placeholder="https://…"></label><label>Kind<select name="kind"><option value="manual">Manual collection</option><option value="smart">Smart collection</option></select></label><section id="collection-rule-editor" hidden><h3>Criteria</h3><label>Match<select name="ruleMode"><option value="all">All criteria</option><option value="any">Any criterion</option></select></label><div id="collection-rule-rows"></div><button type="button" id="add-collection-rule">Add criterion</button></section><p id="collection-edit-error" role="alert" hidden></p><div class="collection-dialog-actions"><button type="button" data-close-collection>Cancel</button><button type="button" id="delete-collection" hidden>Remove collection</button><button type="submit">Save collection</button></div></form></dialog><dialog id="collection-member-picker" aria-labelledby="collection-member-title"><form id="collection-member-form"><h2 id="collection-member-title">Add a library entry</h2><p>This adds a reference to the collection. Its novel links stay as they are.</p><label>Entry<select id="collection-member-target" required></select></label><p id="collection-member-error" role="alert" hidden></p><div class="collection-dialog-actions"><button type="button" data-close-member>Cancel</button><button type="submit">Add entry</button></div></form></dialog>`;}
function render(record){
 const detail=Boolean(record),manual=record?.kind==='manual';
 return renderDirectoryPage({id:'collections-directory',title:record?.name||'Collections',singular:detail?'entry':'collection',plural:detail?'entries':'collections',eyebrow:detail?(manual?'Manual collection':'Smart collection'):'YOUR LIBRARY',description:record?.summary||(!detail?'Gather related material without making copies.':''),script:'/collections/directory.js?v=__WTF_ASSET_REVISION__',styles:['/dashboard/shell.css?v=__WTF_ASSET_REVISION__','/collections/collections.css?v=__WTF_ASSET_REVISION__'],leadingAction:detail?{label:'All collections',href:'/collections/'}:null,primaryAction:{id:'edit-collection',label:detail?'Edit collection':'New collection',icon:'+'},searchPlaceholder:detail?'Search this collection…':'Search collections…',views:[{value:'cards',label:'Cards'},{value:'list',label:'List'}],sorts:[{value:'order',label:detail?'Collection order':'Recently updated'},{value:'name',label:'Alphabetical'}],empty:{title:detail?'No entries yet':'No collections yet',description:detail?(manual?'Add entries from your library.':'Entries matching the criteria will appear here.'):'Create a manual collection or save smart criteria.'},slots:{leadingActions:manual?'<button type="button" class="directory-action" id="add-collection-member">Add entry</button><button type="button" class="directory-action" id="save-collection-order" hidden>Save order</button>':'',beforeList:detail?'<p id="collection-rule-summary" class="collection-criteria" role="status"></p>':'',dialogs:dialogs()+`<script id="collection-data" type="application/json">${jsonData(record)}</script>`}});
}
export async function collectionPageRoute(request,env){
 const url=new URL(request.url),path=url.pathname;
 if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});
 if(path==='/collections')return Response.redirect(url.origin+path+'/'+url.search,308);
 if(path==='/collections/'||path==='/collections/index.html')return new Response(request.method==='HEAD'?null:render(null),{headers});
 const match=path.match(/^\/collections\/([0-9a-f-]{36})\/?$/i);
 if(!match)return new Response('Collection not found.',{status:404,headers:{'cache-control':'no-store'}});
 if(!path.endsWith('/'))return Response.redirect(url.origin+path+'/'+url.search,308);
 const owner=request.headers.get('oai-authenticated-user-id');if(!owner)return new Response('Sign in to access your collections.',{status:401,headers:{'cache-control':'no-store'}});
 try{const record=await collectionRepository(env.DB).get(owner,match[1]);return record?new Response(request.method==='HEAD'?null:render(record),{headers}):new Response('Collection not found.',{status:404,headers:{'cache-control':'no-store'}});}catch(error){console.error('Collection page failed',error.message);return new Response('This collection could not be loaded.',{status:503,headers:{'cache-control':'no-store'}});}
}
