import { seedFactions } from '../public/characters/factions.js';
import { blankFaction } from '../public/factions/template.js';
const details={
 'sample-ember':{type:'House',status:'Active',motto:'Every promise leaves a trace',location:'The capital',leaderId:'claude',summary:'Archivists and diplomats who preserve the treaties holding a fractured kingdom together.',introduction:'The House of Ember safeguards the agreements between rival houses. Its scribes record not only what was promised, but the circumstances and witnesses that gave each promise meaning.',origins:'The house grew around a community of scribes entrusted with keeping copies of disputed agreements.',presentDay:'A sealed royal accord has disappeared from its archive. Claude must decide whether preserving the peace still justifies protecting the secrets of the past.',ideology:'Written promises carry obligations beyond the ambitions of the rulers who signed them.',purpose:'Preserve the treaties and mediate disputes between the houses.',powers:'Archival research, witness testimony, and patient diplomacy.',hierarchy:'Senior archivists oversee the collections; scribes and mediators carry the house’s work beyond its walls.',questions:'Who benefits from the missing accord?\nWhat does the house refuse to record?'},
 'sample-lantern':{type:'Guild',status:'Active',motto:'A path where none existed',leaderId:'gpt',location:'The river workshops',summary:'Inventors and builders working to reconnect the kingdom’s isolated cities.',introduction:'The Lantern Guild brings together craftspeople who turn salvaged materials and ambitious ideas into practical machines. Its proposed transport network could transform travel across the kingdom.',origins:'The guild’s reputation grew through the rebuilding of crossings and workshops after a flood.',presentDay:'GPT’s new transport network relies on a power source whose origin remains uncertain.',purpose:'Connect isolated communities through shared infrastructure.',powers:'Engineering, improvisation, and the coordination of skilled workshops.',resources:'River workshops, salvaged machinery, and the support of influential patrons.',questions:'Who controls the network once it is built?\nWhat is the true cost of its power source?'},
 'sample-archive':{type:'Organization',status:'Active',leaderId:'deepseek',location:'Beneath the capital',motto:'Look beneath the accepted story',summary:'Scholars and investigators recovering the histories buried beneath the capital.',introduction:'The Subterranean Archive studies the ruins below the city. Its discoveries challenge the kingdom’s founding legend and draw unwanted attention from those invested in the official account.',origins:'Evidence recovered from an older buried settlement brought investigators together around unanswered questions.',presentDay:'DeepSeek has found a pattern that connects ancient foundations, a missing treaty, and the Lantern Guild’s machines.',ideology:'An explanation must survive scrutiny of the evidence.',purpose:'Recover and understand the kingdom’s buried history.',powers:'Excavation, inscription analysis, and pattern recognition.',questions:'Which discoveries are too dangerous to reveal?\nWho sealed the oldest chambers?'},
 'sample-horizon':{type:'Guild',status:'Active',leaderId:'gemini',motto:'Every place has more than one story',summary:'Explorers and interpreters mapping the kingdom through landscapes, voices, and dreams.',introduction:'The Horizon Cartographers gather routes, songs, sketches, and local accounts into maps that preserve different ways of understanding a place.',presentDay:'Gemini has returned with paired maps that point toward a city missing from official history.',purpose:'Record unfamiliar places and help others navigate between them.',powers:'Exploration, interpretation, and attentive observation.',traditions:'Travelers bring back songs and everyday stories alongside geographic notes.',questions:'Who decides which map is true?\nWhat responsibility does a guide owe the people who follow?'}
};
export async function factionCatalog(db,owner){
 const [custom,profiles]=await Promise.all([db.listFactions(owner),db.listFactionProfiles(owner)]);
 const overrides=new Map(profiles.map(p=>[p.id,p]));
 return [...seedFactions,...custom].map(f=>({...blankFaction(),...details[f.id],...f,version:0,schemaVersion:1,...overrides.get(f.id)}));
}
export function attachFactionNames(cast,factions){return cast.map(c=>({...c,affiliation:factions.find(f=>f.id===c.factionId)?.name??c.affiliation}));}
