import { templateSections } from '../public/characters/template.js';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const value = text => text?.trim() ? `<p class="written-text">${escape(text)}</p>` : '<p class="section-note">Not yet added.</p>';
export function renderProfile(character, cast) {
 const name=escape(character.name.trim() || 'Untitled character');
 const initials=escape(character.name.trim().split(/\s+/).slice(0,2).map(n=>n[0]||'').join('').toUpperCase()||'?');
 const contents=templateSections.map(s=>`<li><a href="#${s.id}">${escape(s.title)}</a></li>`).join('');
 const facts=[['Name',character.name],['Known as',character.title],['Story role',character.storyRole],['Moral alignment',character.alignment],['Occupation',character.roles],['Faction',character.affiliation]];
 const body=templateSections.map(section=>{
  if(section.id==='identity') return '';
  if(section.id==='relationships') return `<section id="relationships"><h2>Relationships</h2>${character.relationships.length ? `<ul>${character.relationships.map(r=>{const target=cast.find(c=>c.id===r.targetId);return `<li><a href="/characters/${escape(r.targetId)}/">${escape(target?.name||'Untitled character')}</a>${r.type ? ' — '+escape(r.type) : ''}${value(r.description)}</li>`;}).join('')}</ul>` : value('')}</section>`;
  return `<section id="${section.id}"${section.id==='personality'?' class="full-width"':''}><h2>${escape(section.title)}</h2>${section.fields.map(([key,label])=>`<h3>${escape(label)}</h3>${value(character[key])}`).join('')}</section>`;
 }).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${name} — Write to Freedom</title><link rel="icon" href="/crest.svg"><link rel="stylesheet" href="/characters/profile.css"><style>.written-text{white-space:pre-wrap;overflow-wrap:anywhere}.edit-link{padding:5px 10px;border:1px solid #527fdb;border-radius:3px;background:#36c;color:white;font-size:14px}</style></head><body><header class="site-header"><a class="brand" href="/"><img src="/crest.svg" width="35" height="40" alt=""><span>Write to Freedom<small>A Free Novelpedia</small></span></a><a href="/characters/">← All characters</a></header><div class="page-layout"><aside class="desktop-contents"><nav aria-label="Profile contents"><h2>Contents</h2><ol>${contents}</ol></nav></aside><main id="profile"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/characters/">Characters</a> / <span aria-current="page">${name}</span></nav><div class="title-row"><h1>${name}</h1><a class="edit-link" href="/characters/edit/?id=${escape(character.id)}">Edit character</a></div><div class="article-bar"><span class="current-view">Character profile</span><a href="#relationships">${character.relationships.length} relationships</a></div><p class="byline">From Write to Freedom, a free novelpedia.</p><details class="mobile-contents"><summary>Contents</summary><nav aria-label="Profile sections"><ol>${contents}</ol></nav></details><article><aside class="infobox" id="identity" aria-label="Character information"><h2>${name}</h2><p class="infobox-title">${escape(character.title)}</p><div class="identity-panel blue"><span class="monogram">${initials}</span></div><h3>Character information</h3><dl>${facts.map(([key,text])=>`<div><dt>${escape(key)}</dt><dd>${escape(text||'Not yet added')}</dd></div>`).join('')}</dl></aside>${body}</article><footer class="profile-footer"><a href="/characters/">← Back to characters</a><a href="#profile">Back to top ↑</a></footer></main></div></body></html>`;
}
