import {ancestors} from '../public/locations/data.js';
import {escape} from './render-profile.js';
import {citySections,validImageUrl} from '../public/locations/cities/template.js';
export function renderCity(city,locations,cast){
 const name=escape(city.name),countries=locations.filter(l=>l.type==='country'),parent=countries.find(l=>l.id===city.parentId),landmarks=locations.filter(l=>l.type==='landmark'&&ancestors(l,locations).some(a=>a.id===city.id));
 const contents=citySections.map(s=>`<li><a href="#${s.id}">${escape(s.title)}</a></li>`).join('');
 function field([key,label,type]){
  const value=city[key]||'',attrs=`id="field-${key}" name="${key}" aria-label="${escape(label)}"`;let control;
  if(type==='country'||type==='character'){
   const choices=type==='country'?countries:cast;control=`<select ${attrs}${type==='country'?' required':''}><option value="">Not yet chosen</option>${choices.map(c=>`<option value="${escape(c.id)}"${c.id===value?' selected':''}>${escape(c.name||'Untitled character')}</option>`).join('')}</select>`;
   if(type==='country')control+=`<a class="country-link" data-country-link href="/locations/countries/${escape(value)}/">${escape(parent?.name||'Open country')}</a>`;
   if(type==='character')control+=`<a class="person-link" data-for="${key}" href="/characters/${escape(value)}/"${!value?' hidden':''}>Open profile →</a>`;
  }else if(type==='textarea')control=`<textarea ${attrs} rows="2" maxlength="10000" placeholder="Add ${escape(label.toLowerCase())}…">${escape(value)}</textarea>`;
  else control=`<input ${attrs} type="${type==='url'?'url':'text'}"${key==='name'?' required':''}${type==='url'?' pattern="https://.*" title="Use an HTTPS image URL"':''} autocomplete="off" maxlength="${key==='name'?160:type==='url'?2048:10000}" value="${escape(value)}" placeholder="${type==='url'?'https://…':'Add '+escape(label.toLowerCase())+'…'}">`;
  return `<div class="inline-field${type==='textarea'?' prose-field':''}"><label for="field-${key}">${escape(label)}</label>${control}</div>`;
 }
 function media(key,label){const value=city[key]||'',visible=value&&validImageUrl(value);return `<figure class="country-media${key==='mapUrl'?' country-map':key==='skylineUrl'?' city-view':''}"><img data-image="${key}" alt="${escape(label)}" referrerpolicy="no-referrer"${visible?` src="${escape(value)}"`:' hidden'}><figcaption><details${visible?'':' open'}><summary>${label}</summary>${field([key,label+' image URL','url'])}</details><small class="image-error" data-image-error="${key}" hidden>Image unavailable. Check its URL.</small></figcaption></figure>`;}
 const areas=locations.filter(l=>l.type==='area'&&ancestors(l,locations).some(a=>a.id===city.id));
 const areaList=areas.length?`<h3>Areas</h3><ul class="city-landmarks">${areas.map(a=>`<li><a href="/locations/#location-${escape(a.id)}">${escape(a.name)}</a> <small>(${escape(a.areaType||'Area')})</small></li>`).join('')}</ul>`:'';
 const places=areaList+(landmarks.length?`<ul class="city-landmarks">${landmarks.map(l=>`<li><a href="/locations/#location-${escape(l.id)}">${escape(l.name)}</a>${l.parentId!==city.id?` <small>— ${escape(ancestors(l,locations).filter(a=>a.type==='area').map(a=>a.name).join(' › '))}</small>`:''}</li>`).join('')}</ul>`:'<p class="section-note">No landmarks recorded yet. Add a landmark in Locations and choose this city or one of its areas.</p>');
 const body=citySections.filter(s=>!['identity','symbols'].includes(s.id)).map(s=>`<section id="${s.id}" class="profile-section${s.id==='places'?' full-width':''}">${s.id==='overview'?'':`<h2>${escape(s.title)}</h2>`}${s.id==='places'?places+'<p class="section-note"><a href="/locations/">Manage locations</a></p>':''}${s.fields.map(field).join('')}</section>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${name} — Write to Freedom</title><link rel="icon" href="/crest.svg"><link rel="stylesheet" href="/characters/profile.css"><link rel="stylesheet" href="/characters/profile-editor.css"><link rel="stylesheet" href="/locations/countries/profile.css"><link rel="stylesheet" href="/locations/cities/profile.css"><script type="module" src="/locations/cities/profile.js"></script></head><body><header class="site-header"><a class="brand" href="/"><img src="/crest.svg" width="35" height="40" alt=""><span>Write to Freedom<small>A Free Novelpedia</small></span></a><a href="/locations/">← All locations</a></header><div class="page-layout"><aside class="desktop-contents"><nav aria-label="City contents"><h2>Contents</h2><ol>${contents}</ol></nav></aside><main id="profile"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/locations/">Locations</a> / <span aria-current="page" data-display-name>${name}</span></nav><div class="title-row"><h1><button id="edit-name" type="button" title="Edit city name" data-display-name>${name}</button></h1></div><form id="profile-form" data-id="${escape(city.id)}" data-version="${city.version}"><div class="article-bar"><span class="current-view">City profile</span><div class="save-actions"><span id="save-status" role="status">Saved</span><button id="save-character" type="submit">Save changes</button></div></div><p class="byline">Click any field to edit your city.</p><p id="editor-error" role="alert" hidden></p><noscript>Enable JavaScript to edit and save this profile.</noscript><details class="mobile-contents"><summary>Contents</summary><nav><ol>${contents}</ol></nav></details><fieldset id="editor-fields"><legend class="sr-only">City profile</legend><article><aside class="infobox country-infobox city-infobox" id="identity" aria-label="City information"><h2 id="official-heading">${escape(city.officialName||city.name)}</h2><p class="country-assignment">City in <a data-country-link href="/locations/countries/${escape(city.parentId)}/">${escape(parent?.name||'Country')}</a></p><div id="symbols">${media('skylineUrl','City view')}<div class="country-symbols">${media('flagUrl','Flag')}${media('sealUrl','Seal')}</div><div class="epithet-field">${field(citySections[0].fields.find(f=>f[0]==='motto'))}</div>${media('mapUrl','Map')}</div><h3>City information</h3>${citySections[0].fields.filter(f=>!['motto'].includes(f[0])).map(field).join('')}<a class="places-count" href="#places">${landmarks.length} ${landmarks.length===1?'landmark':'landmarks'}</a></aside>${body}</article></fieldset></form><footer class="profile-footer"><a href="/locations/">← Back to locations</a><a href="#profile">Back to top ↑</a></footer></main></div></body></html>`;
}
