import {ancestors} from '../public/locations/data.js';
import {escape} from './render-profile.js';
import {countrySections,validImageUrl} from '../public/locations/countries/template.js';
export function renderCountry(country,locations,cast){
 const name=escape(country.name),cities=locations.filter(l=>l.type==='city'&&l.parentId===country.id),cityIds=new Set(cities.map(c=>c.id)),landmarks=locations.filter(l=>l.type==='landmark'&&ancestors(l,locations).some(a=>cityIds.has(a.id)));
 const contents=countrySections.map(s=>`<li><a href="#${s.id}">${escape(s.title)}</a></li>`).join('');
 function field([key,label,type]){
  const value=country[key]||'',attrs=`id="field-${key}" name="${key}" aria-label="${escape(label)}"`;let control;
  if(type==='city'||type==='character'){
   const choices=type==='city'?cities:cast;control=`<select ${attrs}><option value="">Not yet chosen</option>${choices.map(c=>`<option value="${escape(c.id)}"${c.id===value?' selected':''}>${escape(c.name||'Untitled character')}</option>`).join('')}</select>`;
   if(type==='character')control+=`<a class="person-link" data-for="${key}" href="/characters/${escape(value)}/"${!value?' hidden':''}>Open profile →</a>`;
  }else if(type==='textarea')control=`<textarea ${attrs} rows="2" maxlength="10000" placeholder="Add ${escape(label.toLowerCase())}…">${escape(value)}</textarea>`;
  else control=`<input ${attrs} type="${type==='url'?'url':'text'}"${key==='name'?' required':''}${type==='url'?' pattern="https://.*" title="Use an HTTPS image URL"':''} autocomplete="off" maxlength="${key==='name'?160:type==='url'?2048:10000}" value="${escape(value)}" placeholder="${type==='url'?'https://…':'Add '+escape(label.toLowerCase())+'…'}">`;
  return `<div class="inline-field${type==='textarea'?' prose-field':''}"><label for="field-${key}">${escape(label)}</label>${control}</div>`;
 }
 function media(key,label){const value=country[key]||'',visible=value&&validImageUrl(value);return `<figure class="country-media${key==='mapUrl'?' country-map':''}"><img data-image="${key}" alt="${escape(label)}" referrerpolicy="no-referrer"${visible?` src="${escape(value)}"`:' hidden'}><figcaption><details${visible?'':' open'}><summary>${label}</summary>${field([key,label+' image URL','url'])}</details><small class="image-error" data-image-error="${key}" hidden>Image unavailable. Check its URL.</small></figcaption></figure>`;}
 const places=cities.length?`<div class="table-scroll"><table class="country-places"><thead><tr><th scope="col">City</th><th scope="col">Landmarks</th></tr></thead><tbody>${cities.map(city=>`<tr><th scope="row"><a href="/locations/cities/${escape(city.id)}/">${escape(city.name)}</a></th><td>${landmarks.filter(l=>ancestors(l,locations).some(a=>a.id===city.id)).map(l=>`<a href="/locations/#location-${escape(l.id)}">${escape(l.name)}</a>`).join('<br>')||'None recorded'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="section-note">No cities recorded yet. Add a city in Locations and choose this country.</p>';
 const body=countrySections.filter(s=>!['identity','symbols'].includes(s.id)).map(s=>`<section id="${s.id}" class="profile-section${s.id==='places'?' full-width':''}">${s.id==='overview'?'':`<h2>${escape(s.title)}</h2>`}${s.id==='places'?places+'<p class="section-note"><a href="/locations/">Manage locations</a></p>':''}${s.fields.map(field).join('')}</section>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${name} — Write to Freedom</title><link rel="icon" href="/crest.svg"><link rel="stylesheet" href="/characters/profile.css"><link rel="stylesheet" href="/characters/profile-editor.css"><link rel="stylesheet" href="/locations/countries/profile.css"><script type="module" src="/locations/countries/profile.js"></script></head><body><header class="site-header"><a class="brand" href="/"><img src="/crest.svg" width="35" height="40" alt=""><span>Write to Freedom<small>A Free Novelpedia</small></span></a><a href="/locations/">← All locations</a></header><div class="page-layout"><aside class="desktop-contents"><nav aria-label="Country contents"><h2>Contents</h2><ol>${contents}</ol></nav></aside><main id="profile"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/locations/">Locations</a> / <span aria-current="page" data-display-name>${name}</span></nav><div class="title-row"><h1><button id="edit-name" type="button" title="Edit country name" data-display-name>${name}</button></h1></div><form id="profile-form" data-id="${escape(country.id)}" data-version="${country.version}"><div class="article-bar"><span class="current-view">Country profile</span><div class="save-actions"><span id="save-status" role="status">Saved</span><button id="save-character" type="submit">Save changes</button></div></div><p class="byline">Click any field to edit your country.</p><p id="editor-error" role="alert" hidden></p><noscript>Enable JavaScript to edit and save this profile.</noscript><details class="mobile-contents"><summary>Contents</summary><nav><ol>${contents}</ol></nav></details><fieldset id="editor-fields"><legend class="sr-only">Country profile</legend><article><aside class="infobox country-infobox" id="identity" aria-label="Country information"><h2 id="official-heading">${escape(country.officialName||country.name)}</h2><div id="symbols"><div class="country-symbols">${media('flagUrl','Flag')}${media('coatOfArmsUrl','Coat of arms')}</div><div class="epithet-field">${field(countrySections[0].fields.find(f=>f[0]==='motto'))}</div>${field(countrySections[0].fields.find(f=>f[0]==='anthem'))}${media('mapUrl','Map')}</div><h3>Country information</h3>${countrySections[0].fields.filter(f=>!['motto','anthem'].includes(f[0])).map(field).join('')}<a class="places-count" href="#places">${cities.length} ${cities.length===1?'city':'cities'} · ${landmarks.length} ${landmarks.length===1?'landmark':'landmarks'}</a></aside>${body}</article></fieldset></form><footer class="profile-footer"><a href="/locations/">← Back to locations</a><a href="#profile">Back to top ↑</a></footer></main></div></body></html>`;
}
